{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0e84ad8d-211c-42ac-9f15-e7ccb5c92afd",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting streamlit\n",
      "  Downloading streamlit-1.56.0-py3-none-any.whl.metadata (9.8 kB)\n",
      "Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)\n",
      "  Downloading altair-6.1.0-py3-none-any.whl.metadata (11 kB)\n",
      "Requirement already satisfied: blinker<2,>=1.5.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from streamlit) (1.9.0)\n",
      "Requirement already satisfied: cachetools<8,>=5.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from streamlit) (5.5.1)\n",
      "Requirement already satisfied: click<9,>=7.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from streamlit) (8.1.8)\n",
      "Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)\n",
      "  Downloading gitpython-3.1.47-py3-none-any.whl.metadata (14 kB)\n",
      "Requirement already satisfied: numpy<3,>=1.23 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from streamlit) (1.26.4)\n",
      "Requirement already satisfied: packaging>=20 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from streamlit) (24.2)\n",
      "Requirement already satisfied: pandas<4,>=1.4.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from streamlit) (2.2.3)\n",
      "Requirement already satisfied: pillow<13,>=7.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from streamlit) (11.1.0)\n",
      "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
      "  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)\n",
      "Requirement already satisfied: protobuf<8,>=3.20 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from streamlit) (5.29.3)\n",
      "Collecting pyarrow>=7.0 (from streamlit)\n",
      "  Downloading pyarrow-24.0.0-cp313-cp313-macosx_12_0_arm64.whl.metadata (3.0 kB)\n",
      "Requirement already satisfied: requests<3,>=2.27 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from streamlit) (2.32.3)\n",
      "Requirement already satisfied: tenacity<10,>=8.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from streamlit) (9.0.0)\n",
      "Collecting toml<2,>=0.10.1 (from streamlit)\n",
      "  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)\n",
      "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from streamlit) (6.4.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.10.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from streamlit) (4.12.2)\n",
      "Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.5)\n",
      "Requirement already satisfied: jsonschema>=3.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.23.0)\n",
      "Requirement already satisfied: narwhals>=2.4.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.20.0)\n",
      "Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
      "  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas<4,>=1.4.0->streamlit) (2025.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas<4,>=1.4.0->streamlit) (2025.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.4.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (2.3.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (2025.1.31)\n",
      "Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
      "  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.2)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.1.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2024.10.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.36.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.22.3)\n",
      "Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)\n",
      "Downloading streamlit-1.56.0-py3-none-any.whl (9.1 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m9.1/9.1 MB\u001b[0m \u001b[31m38.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m31m41.6 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hDownloading altair-6.1.0-py3-none-any.whl (796 kB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m797.0/797.0 kB\u001b[0m \u001b[31m21.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hDownloading gitpython-3.1.47-py3-none-any.whl (209 kB)\n",
      "Downloading pyarrow-24.0.0-cp313-cp313-macosx_12_0_arm64.whl (35.0 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m35.0/35.0 MB\u001b[0m \u001b[31m39.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0mm eta \u001b[36m0:00:01\u001b[0m0:01\u001b[0m01\u001b[0m\n",
      "\u001b[?25hDownloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m11.3/11.3 MB\u001b[0m \u001b[31m39.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m1m41.3 MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hDownloading toml-0.10.2-py2.py3-none-any.whl (16 kB)\n",
      "Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)\n",
      "Downloading smmap-5.0.3-py3-none-any.whl (24 kB)\n",
      "Installing collected packages: toml, smmap, pyarrow, pydeck, gitdb, gitpython, altair, streamlit\n",
      "Successfully installed altair-6.1.0 gitdb-4.0.12 gitpython-3.1.47 pyarrow-24.0.0 pydeck-0.9.2 smmap-5.0.3 streamlit-1.56.0 toml-0.10.2\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m25.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m26.0.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49m/Library/Frameworks/Python.framework/Versions/3.13/bin/python3 -m pip install --upgrade pip\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install streamlit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "d7d680f4-6794-49c8-a50c-ead8fea45ce7",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting psycopg2-binary\n",
      "  Downloading psycopg2_binary-2.9.12-cp313-cp313-macosx_11_0_arm64.whl.metadata (4.9 kB)\n",
      "Downloading psycopg2_binary-2.9.12-cp313-cp313-macosx_11_0_arm64.whl (3.8 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m3.8/3.8 MB\u001b[0m \u001b[31m33.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hInstalling collected packages: psycopg2-binary\n",
      "Successfully installed psycopg2-binary-2.9.12\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip is available: \u001b[0m\u001b[31;49m25.0.1\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m26.0.1\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49m/Library/Frameworks/Python.framework/Versions/3.13/bin/python3 -m pip install --upgrade pip\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install psycopg2-binary"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "ac340c0d-3af7-4124-8c35-8c00a85e5351",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import psycopg2\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d0618e16-1ad6-47b3-a83e-b773cee16003",
   "metadata": {},
   "source": [
    "# Setting Up Web App"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6ebab76b-b42b-441e-b14e-629d9754d95b",
   "metadata": {},
   "outputs": [],
   "source": [
    "st.set_page_config(page_title=\"Literary Trends Warehouse\", layout=\"wide\")\n",
    "\n",
    "def get_connection():\n",
    "    return psycopg2.connect(\n",
    "        host='localhost',\n",
    "        database='bestsellers',\n",
    "        user='postgres',\n",
    "        password='123456'\n",
    "    )\n",
    "\n",
    "conn = get_connection()\n",
    "\n",
    "def run_query(query):\n",
    "    return pd.read_sql_query(query, conn)\n",
    "\n",
    "st.title(\"Literary Trends Warehouse\")\n",
    "st.write(\"Explore 25+ years of NYT Critics Picks and Bestseller data.\")\n",
    "\n",
    "page = st.sidebar.selectbox(\"Choose a View\", [\n",
    "    \"Top 10 Longest Running Bestsellers\",\n",
    "    \"Authors with the Most Bestsellers\",\n",
    "    \"Hardcover Fiction Rankings\",\n",
    "    \"Most Frequent Authors\",\n",
    "    \"Critics vs Bestsellers Overlap\",\n",
    "    \"Top Publishers by Shelf Life\",\n",
    "    \"Books Over 20 Weeks but Never Top 5\",\n",
    "    \"Books That Debuted at Number 1\",\n",
    "    \"Publishers: Fiction vs Nonfiction\",\n",
    "    \"Authors in Both Critics and Bestsellers\"\n",
    "])\n",
    "\n",
    "if page == \"Top 10 Longest Running Bestsellers\":\n",
    "    st.header(\"Top 10 Longest Running Bestsellers\")\n",
    "    df = run_query(\"\"\"\n",
    "        SELECT title, author, MAX(weeks_on_list) as total_weeks, MIN(rank) as best_rank\n",
    "        FROM bestsellers\n",
    "        GROUP BY title, author\n",
    "        ORDER BY total_weeks DESC\n",
    "        LIMIT 10\n",
    "    \"\"\")\n",
    "    st.dataframe(df)\n",
    "    fig, ax = plt.subplots()\n",
    "    ax.barh(df['title'], df['total_weeks'], color='teal')\n",
    "    ax.set_xlabel(\"Weeks on List\")\n",
    "    ax.set_title(\"Top 10 Longest Running Bestsellers\")\n",
    "    plt.tight_layout()\n",
    "    st.pyplot(fig)\n",
    "\n",
    "elif page == \"Authors with the Most Bestsellers\":\n",
    "    st.header(\"Authors with the Most Unique Bestsellers\")\n",
    "    df = run_query(\"\"\"\n",
    "        SELECT author, COUNT(DISTINCT title) as unique_bestsellers,\n",
    "        AVG(weeks_on_list)::NUMERIC(10,2) as avg_weeks_per_book\n",
    "        FROM bestsellers\n",
    "        GROUP BY author\n",
    "        HAVING COUNT(DISTINCT title) > 1\n",
    "        ORDER BY unique_bestsellers DESC\n",
    "        LIMIT 10\n",
    "    \"\"\")\n",
    "    st.dataframe(df)\n",
    "    fig, ax = plt.subplots()\n",
    "    ax.bar(df['author'], df['unique_bestsellers'], color='steelblue')\n",
    "    plt.xticks(rotation=45, ha='right')\n",
    "    ax.set_ylabel(\"Unique Bestsellers\")\n",
    "    ax.set_title(\"Authors with the Most Unique Bestsellers\")\n",
    "    plt.tight_layout()\n",
    "    st.pyplot(fig)\n",
    "\n",
    "elif page == \"Hardcover Fiction Rankings\":\n",
    "    st.header(\"Hardcover Fiction - Most Weeks on List\")\n",
    "    df = run_query(\"\"\"\n",
    "        SELECT DISTINCT title, author,\n",
    "        FIRST_VALUE(rank) OVER (PARTITION BY title ORDER BY list_date ASC) as starting_rank,\n",
    "        LAST_VALUE(rank) OVER (PARTITION BY title ORDER BY list_date ASC\n",
    "            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as current_rank,\n",
    "        COUNT(*) OVER (PARTITION BY title) as times_on_list\n",
    "        FROM bestsellers\n",
    "        WHERE list_name = 'hardcover-fiction'\n",
    "        ORDER BY times_on_list DESC\n",
    "        LIMIT 20\n",
    "    \"\"\")\n",
    "    st.dataframe(df)\n",
    "\n",
    "elif page == \"Most Frequent Authors\":\n",
    "    st.header(\"Most Frequent Authors on the Bestseller List\")\n",
    "    df = run_query(\"\"\"\n",
    "        SELECT author, COUNT(*) as appearances\n",
    "        FROM bestsellers\n",
    "        GROUP BY author\n",
    "        ORDER BY appearances DESC\n",
    "        LIMIT 10\n",
    "    \"\"\")\n",
    "    st.dataframe(df)\n",
    "    fig, ax = plt.subplots()\n",
    "    ax.bar(df['author'], df['appearances'], color='coral')\n",
    "    plt.xticks(rotation=45, ha='right')\n",
    "    ax.set_ylabel(\"Appearances\")\n",
    "    ax.set_title(\"Most Frequent Authors on the Bestseller List\")\n",
    "    plt.tight_layout()\n",
    "    st.pyplot(fig)\n",
    "\n",
    "elif page == \"Critics vs Bestsellers Overlap\":\n",
    "    st.header(\"Books That Were Both Critically Reviewed and Bestsellers\")\n",
    "    df = run_query(\"\"\"\n",
    "        SELECT b.title, b.author, MAX(b.weeks_on_list) as max_weeks,\n",
    "        COUNT(c.headline) as review_count\n",
    "        FROM bestsellers b\n",
    "        LEFT JOIN critics c ON LOWER(b.title) = LOWER(c.headline)\n",
    "        GROUP BY b.title, b.author\n",
    "        HAVING COUNT(c.headline) > 0\n",
    "        ORDER BY review_count DESC, max_weeks DESC\n",
    "    \"\"\")\n",
    "    st.dataframe(df)\n",
    "    fig, ax = plt.subplots()\n",
    "    ax.scatter(df['review_count'], df['max_weeks'], color='teal', alpha=0.5)\n",
    "    ax.set_xlabel(\"Number of Critic Reviews\")\n",
    "    ax.set_ylabel(\"Max Weeks on List\")\n",
    "    ax.set_title(\"Do Critic Reviews Lead to More Weeks on List?\")\n",
    "    plt.tight_layout()\n",
    "    st.pyplot(fig)\n",
    "\n",
    "elif page == \"Top Publishers by Shelf Life\":\n",
    "    st.header(\"Top 10 Publishers by Total Shelf Life\")\n",
    "    df = run_query(\"\"\"\n",
    "        SELECT publisher, COUNT(DISTINCT title) as total_unique_books,\n",
    "        SUM(weeks_on_list) as total_shelf_life\n",
    "        FROM bestsellers\n",
    "        GROUP BY publisher\n",
    "        ORDER BY total_shelf_life DESC\n",
    "        LIMIT 10\n",
    "    \"\"\")\n",
    "    st.dataframe(df)\n",
    "    fig, ax = plt.subplots()\n",
    "    ax.barh(df['publisher'], df['total_shelf_life'], color='purple')\n",
    "    ax.set_xlabel(\"Total Weeks on List\")\n",
    "    ax.set_title(\"Top Publishers by Total Shelf Life\")\n",
    "    plt.tight_layout()\n",
    "    st.pyplot(fig)\n",
    "\n",
    "elif page == \"Books Over 20 Weeks but Never Top 5\":\n",
    "    st.header(\"Books on List Over 20 Weeks but Never Ranked in Top 5\")\n",
    "    df = run_query(\"\"\"\n",
    "        SELECT title, author, weeks_on_list, rank as final_rank\n",
    "        FROM bestsellers\n",
    "        WHERE weeks_on_list > 20 AND rank > 5\n",
    "        ORDER BY weeks_on_list DESC\n",
    "    \"\"\")\n",
    "    st.dataframe(df)\n",
    "\n",
    "elif page == \"Books That Debuted at Number 1\":\n",
    "    st.header(\"Books That Debuted at Number 1\")\n",
    "    df = run_query(\"\"\"\n",
    "        SELECT title, author, list_date, weeks_on_list\n",
    "        FROM bestsellers\n",
    "        WHERE rank = 1\n",
    "        ORDER BY weeks_on_list DESC\n",
    "        LIMIT 10\n",
    "    \"\"\")\n",
    "    st.dataframe(df)\n",
    "\n",
    "elif page == \"Publishers: Fiction vs Nonfiction\":\n",
    "    st.header(\"Most Prolific Publishers: Fiction vs Nonfiction\")\n",
    "    df = run_query(\"\"\"\n",
    "        SELECT publisher, list_name, COUNT(DISTINCT title) as total_titles\n",
    "        FROM bestsellers\n",
    "        GROUP BY publisher, list_name\n",
    "        ORDER BY total_titles DESC\n",
    "        LIMIT 10\n",
    "    \"\"\")\n",
    "    st.dataframe(df)\n",
    "    fiction = df[df['list_name'] == 'hardcover-fiction']\n",
    "    nonfiction = df[df['list_name'] == 'hardcover-nonfiction']\n",
    "    fig, ax = plt.subplots()\n",
    "    x = range(len(fiction))\n",
    "    ax.bar(x, fiction['total_titles'].values, width=0.4, label='Fiction', color='steelblue', alpha=0.7)\n",
    "    ax.bar([i + 0.4 for i in x], nonfiction['total_titles'].values[:len(fiction)], width=0.4, label='Nonfiction', color='coral', alpha=0.7)\n",
    "    ax.set_xticks([i + 0.2 for i in x])\n",
    "    ax.set_xticklabels(fiction['publisher'].values, rotation=45, ha='right')\n",
    "    ax.set_ylabel(\"Total Titles\")\n",
    "    ax.set_title(\"Publishers: Fiction vs Nonfiction\")\n",
    "    ax.legend()\n",
    "    plt.tight_layout()\n",
    "    st.pyplot(fig)\n",
    "\n",
    "elif page == \"Authors in Both Critics and Bestsellers\":\n",
    "    st.header(\"Authors Who Appear in Both Critics Picks and Bestsellers\")\n",
    "    df = run_query(\"\"\"\n",
    "        SELECT DISTINCT b.author\n",
    "        FROM bestsellers b\n",
    "        INNER JOIN critics c ON LOWER(b.author) LIKE LOWER('%' || c.byline || '%')\n",
    "        ORDER BY b.author\n",
    "        LIMIT 10\n",
    "    \"\"\")\n",
    "    st.dataframe(df)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.13",
   "language": "python",
   "name": "python3.13"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
